name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # or your preferred version

      # Step 3: Terraform init
      - name: Terraform Init
        run: terraform init
        working-directory: ./root

      # Step 4: Terraform plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./root

      # Optional: Show plan in logs
      - name: Terraform Show Plan
        run: terraform show tfplan
        working-directory: ./root

